[bastion]
bastion.ru-central1-a.internal ansible_host=130.193.51.237

[webservers]
web-01.ru-central1-a.internal ansible_host=192.168.2.27
web-02.ru-central1-b.internal ansible_host=192.168.3.22

[zabbix]
zabbix.ru-central1-a.internal ansible_host=130.193.51.244

[elasticsearch]
elasticsearch.ru-central1-a.internal ansible_host=192.168.2.31

[kibana]
kibana.ru-central1-a.internal ansible_host=62.84.114.229


[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ansible@178.154.202.51"'

