---
- name: install nginx webservers
  hosts: webservers
  become: yes
  roles:
    - nginx

- name: install elasticsearch
  hosts: elasticsearch
  become: yes
  roles:
    - role: elasticsearch

- name: install filebeat web servers
  hosts: webservers
  become: yes
  roles:
    - role: filebeat

- name: install kibana
  hosts: kibana
  become: yes
  roles:
    - role: kibana

- name: postgres for zabbix
  hosts: zabbix
  become: yes
  roles:
    - role: zabbix-db
    - role: community.zabbix.zabbix_server
    - role: community.zabbix.zabbix_web
    - role: zabbix-web-config

- name: Install Zabbix Agent on all hosts
  hosts: all
  become: yes
  roles:
    - role: community.zabbix.zabbix_agent

